name: user_list_app
description: "Simple app for assignment"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 # ✅ launcher icon generator

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"  # ✅ your app icon path
